### PR TITLE
Flip postgres-POLYGON to h3 LatLng convertion

### PR DESCRIPTION
**Pull request by zachasme**
There appears to be some trouble around the internal handling of latitude/longitude during polyfill:

```pgsql
SELECT COUNT(*) FROM (
    select h3_polygon_to_cells(st_geographyfromtext('POLYGON((-41 59,-41 89,41 89,41 59,-41 59))'),8)
) q;
```

the above crashes h3-pg. Comparing to h3-py however

```python
import h3
poly = h3.Polygon( [(-41, 59),(-41, 89),(41, 89),(41, 59),(-41, 59)] ) 
x = list(h3.polygon_to_cells(poly,8))
print(len(x)) # prints 36638220
```

After a bit of debugging I've found that flipping x/y -> lat/lng in regions.c, will make the first query work and also produce the same result as the python bindings.

I'm using the branch to investigate further, and ensure I can match the output of the other bindings.

### CODE REVIEW

**Comment by zachasme** [comment]
The flip seems to solve this specific case.

However, the `postgis_raster` tests are failing now. I'll have to look into why next week.

@mngr777 do you have any input on how this change affects the raster code?

**Comment by mngr777** [comment]
The first test query in rasters test checks that different methods generate the same result.
`h3_raster_summary_clip` function uses `h3_polygon_to_cells`, and `h3_raster_summary_centroids` maps the centroid of each pixel to h3 with `h3_lat_lng_to_cell`.

I run the queries manually and `h3_polygon_to_cells` seems to flip the coordinates incorrectly before calling h3 function:
```
psql --csv -c 'SELECT ST_AsText(h3_cell_to_boundary_geometry(h3)) AS geom FROM (SELECT h3_polygon_to_cells(ST_MinConvexHull(rast, 1), 8) AS h3 FROM h3_test_rasters) AS t' > hexagons.csv
psql --csv -c 'SELECT ST_AsText(ST_MinConvexHull(rast, 1)) AS geom FROM h3_test_rasters' > hull.csv
```
The rasters are around lat 51, lon 0 and hexagons are at lat 0, lon 51.

To check if `h3_cell_to_boundary_geometry` works:
```
psql --csv -c "SELECT ST_AsText(h3_cell_to_boundary_geometry('83194afffffffff'::h3index)) AS geom" > hex.csv
```
The hexagon is at lat 51, lon 0, which is correct.

**Comment by mngr777** [comment]
In your example, the coordinates in WKT are lon/lat, but h3-py uses lat/lon coordinates: https://uber.github.io/h3-py/api_reference#h3.Polygon ?

**Comment by zachasme** [comment]
Yes, you I right. The confusion was because the functions are named "lat_lng_to_cell", which doesn't match the WKT coordinates. I'll run this by the guy who sent me the polyfill example, and will probably close this PR. Thanks for the help!

**Pull request closed without merging**
